CREATE TABLE `rout` (
	`PC_Num` INT(11) NOT NULL AUTO_INCREMENT,
	`Ip` CHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`PC_Num`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;

CREATE TABLE `pc` (
	`PC_Id` INT(11) NOT NULL AUTO_INCREMENT,
	`PC_Numb` INT(11) NOT NULL,
	PRIMARY KEY (`PC_Id`),
	INDEX `FK_pc_rout` (`PC_Numb`),
	CONSTRAINT `FK_pc_rout` FOREIGN KEY (`PC_Numb`) REFERENCES `rout` (`PC_Num`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;

CREATE TABLE `user` (
	`id_U` INT(11) NOT NULL AUTO_INCREMENT,
	`UName` VARCHAR(50) NOT NULL,
	`USName` VARCHAR(50) NOT NULL,
	`U_PC` INT(11) NOT NULL,
	PRIMARY KEY (`id_U`),
	INDEX `FK_user_pc` (`U_PC`),
	CONSTRAINT `FK_user_pc` FOREIGN KEY (`U_PC`) REFERENCES `pc` (`PC_Id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;


